In [ ]:
import numpy as np
import pandas as pd

In [ ]:
t = [i*3 for i in range(1, 11)]

In [ ]:
a = [1, 2, 3]
b= [4, 5, 6]

In [ ]:
np1 = np.array(t)

In [ ]:
type(np1)

numpy.ndarray

In [ ]:
np1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np1 + 1

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [ ]:
np1.dtype

dtype('int64')

In [ ]:
np1.shape

(10,)

In [ ]:
np1.mean() ##평균

16.5

In [ ]:
np1.nbytes  ## 전체 바이트

80

In [ ]:
np1.itemsize ##하나하나의 바이트 

8

In [ ]:
c =[a, b]

In [ ]:
c  ##2행 3열

[[1, 2, 3], [4, 5, 6]]

In [ ]:
np2 = np.array(c)

In [ ]:
np2.shape

(2, 3)

In [ ]:
np2[0]

array([1, 2, 3])

In [ ]:
np2[1, 2]

6

In [ ]:
np2[0][1]

2

In [ ]:
np2 +10  

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
np2.T  ## 행과 열의 구조를 바꿈

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np2  ##2차원

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np1 ##1차원                                                                                     

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np1.mean()

16.5

In [ ]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np2.sum()

21

In [ ]:
np2.sum(axis = 0)  ##열의 총합

array([5, 7, 9])

In [ ]:
np2.sum(axis = 1)  ##행의 총합

array([ 6, 15])

In [ ]:
np2.shape

(2, 3)

In [ ]:
tt1 = [i for i in range(2, 21, 2)]
tt2 = [i*3 for i in range(1,11)]
tt3 = [i for i in range(5, 51, 5)]

In [ ]:
tt1, tt2, tt3

([2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
ttt = [tt1, tt2, tt3]
np22 = np.array(ttt)

In [ ]:
ttt

[[2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]]

In [ ]:
type(ttt)

list

In [ ]:
type(np22)

numpy.ndarray

In [ ]:
np22.sum()

550

In [ ]:
np22[0].sum()

110

In [ ]:
np22[1].sum()

165

In [ ]:
np22.sum(axis = 1)

array([110, 165, 275])

In [ ]:
np22.sum(axis = 0)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np22.T

array([[ 2,  3,  5],
       [ 4,  6, 10],
       [ 6,  9, 15],
       [ 8, 12, 20],
       [10, 15, 25],
       [12, 18, 30],
       [14, 21, 35],
       [16, 24, 40],
       [18, 27, 45],
       [20, 30, 50]])

In [ ]:
np22.mean(axis = 1)

array([11. , 16.5, 27.5])

In [ ]:
np22.mean(axis  = 0)

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        , 23.33333333, 26.66666667, 30.        , 33.33333333])

In [ ]:
np23 = np22.T

In [ ]:
np23.mean()

18.333333333333332

In [ ]:
np23.min()

2

In [ ]:
np23.mean(axis = 1)

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        , 23.33333333, 26.66666667, 30.        , 33.33333333])

In [ ]:
np23.min(axis = 0)

array([2, 3, 5])

In [ ]:
np23.shape

(10, 3)

In [ ]:
np23.reshape(5, 6)

array([[ 2,  3,  5,  4,  6, 10],
       [ 6,  9, 15,  8, 12, 20],
       [10, 15, 25, 12, 18, 30],
       [14, 21, 35, 16, 24, 40],
       [18, 27, 45, 20, 30, 50]])

In [ ]:
np23.reshape(2,15)

array([[ 2,  3,  5,  4,  6, 10,  6,  9, 15,  8, 12, 20, 10, 15, 25],
       [12, 18, 30, 14, 21, 35, 16, 24, 40, 18, 27, 45, 20, 30, 50]])

In [ ]:
np24 = np.array([i for i in range(1, 25)])

In [ ]:
np24

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
np24.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np24.reshape(3, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np24.reshape(6, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
 np11 = np.array([2, 4, 6, 8, 10])  ## dtype('int64') 각각이 8바이트이고 총 40바이트다.

In [ ]:
np11.

dtype('int64')

In [ ]:
 np12 = np.array([2, 4, 6, 8, 10], dtype= np.int16) ##각각이 2바이트이고 총 10 바이트가 된다

In [ ]:
np12.dtype

dtype('int16')

In [ ]:
np12.nbytes

10

In [ ]:
np11.nbytes

40

In [ ]:
np11.itemsize  ##각각이 8바이트!!

8

In [ ]:
np200 = np.array([2.3, 4.5, 6.7]) 

In [ ]:
np200.dtype

dtype('float64')

In [ ]:
np200.nbytes

24

In [ ]:
np200 = np.array([2.3, 4.5, 6.7], dtype=np.float32) 

In [ ]:
np200.nbytes

12

In [ ]:
np200 = np.array([2.3, 4.5, 6.7], dtype=np.float16) 

In [ ]:
np200.nbytes

6

In [109]:
np13 = np.array([2, 4, 5], dtype = 'uint')  ## 데이터를 저장할  음의 부분을 양의 부분에 추가하여 생각

In [111]:
np.empty((2,5))

array([[ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667],
       [20.        , 23.33333333, 26.66666667, 30.        , 33.33333333]])

In [112]:
np.empty((7, 2))

array([[4.68572501e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 7.49959658e+295]])

In [113]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [115]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [119]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [120]:
tt1

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [121]:
np.median(tt1)

11.0