numpy 학습정리

In [ ]:
import numpy as np
import pandas as pd

In [6]:
np11 = np.array([2, 4, 6, 8], dtype=np.int16)
np22 = np.array([3, 6, 9, 12, 15], dtype=np.int16)

In [7]:
np11.shape

(4,)

In [8]:
np11 +=5  ##각각에 5 더하는 것을 broadcasting

In [9]:
np11

array([ 7,  9, 11, 13], dtype=int16)

In [10]:
np11 > 10

array([False, False,  True,  True])

In [11]:
np11 == 11

array([False, False,  True, False])

In [14]:
np11.__lt__(9)  ##같거나 작은 / le 작은 값을 물어볼 때

array([ True, False, False, False])

In [13]:
np11 < 9

array([ True, False, False, False])

In [15]:
np11.size

4

In [16]:
np11.nbytes ## 총 바이트 사이즈

8

In [17]:
np11.itemsize ##개별 바이트 사이즈

2

In [19]:
np11.size

4

In [44]:
np13 = np.arange(1, 11)

In [45]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np13[3:7]

array([4, 5, 6, 7])

In [23]:
np13[3:7]+5

array([ 9, 10, 11, 12])

In [46]:
np13[3:7] += 5

In [47]:
np13

array([ 1,  2,  3,  9, 10, 11, 12,  8,  9, 10])

In [49]:
np14 = np13[3:7] + 5

In [51]:
np14 = np.arange(1, 11)

In [53]:
np15 = np14

In [55]:
np14[2] = 555

In [56]:
np14

array([  1,   2, 555,   4,   5,   6,   7,   8,   9,  10])

In [59]:
np14[-4:] = 0

In [60]:
np14

array([  1,   2, 555,   4,   5,   6,   0,   0,   0,   0])

In [61]:
a1 = [1, 2, 3]

In [70]:
a2 = [2, 4, 6,]

In [71]:
np2 = np.array([a1, a2])

In [74]:
np2 = np.arange(1, 16)

IndexError: ignored

In [99]:
np2[-5:-1]

array([11, 12, 13, 14])

In [78]:
np22 = np2.reshape(3, 5)

In [79]:
np22

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [85]:
np22[0][:],np22[1][:]

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [86]:
np22[ : , :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [110]:
np22[1, 1]

7

In [102]:
np22[0:, -1:]

array([], shape=(0, 1), dtype=int64)

In [103]:
np22[:0, -1:]

array([], shape=(0, 1), dtype=int64)

In [104]:
np22[0:,0:2]  

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

 [0:,0:2] ',' 전은 행의 범위를 나타내고 ','이후는 열의 범위를 나타낸다..

 연속된 값을 표현할 때 [시작 값:end(행의 범위), 시작 값: end(열의 범위)]
범위는 시작값 부터 end-1까지

n-1을 기억하자!! 

In [94]:
np22.T[0:2,0:]

array([[ 1,  6, 11],
       [ 2,  7, 12]])

In [117]:
np3 = np.arange(10, 241,10)

In [118]:
np3.ndim  ## 차원을 나타냄

1

In [119]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [120]:
np3.shape

(24,)

In [121]:
np3.reshape(2, 12)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [122]:
np33 = np3.reshape(2, 12)

In [123]:
np33.ndim

2

In [124]:
np33.reshape(2, 3, 4)

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [125]:
np333 = np33.reshape(2, 3, 4)

In [126]:
np333.ndim

3

In [127]:
np333.shape

(2, 3, 4)

In [135]:
np333[:1, 2:,2:3]  ##슬라이싱

array([[[110]]])

In [136]:
np333[:1, 1:2,1:3]

array([[[60, 70]]])

In [146]:
np333[0,2,2]

110

In [147]:
np33[1,1]  ##인덱싱

140

In [148]:
np33

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])