In [2]:
import numpy as np
import pandas as pd

In [3]:
np3 = np.arange(10, 241,10)

In [4]:
np33 = np3.reshape(2, 12)

In [5]:
np33

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [6]:
np333 = np33.reshape(2, 3, 4)

In [7]:
np333

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [8]:
np333[0, 0, 2]

30

In [11]:
np333[0,2, 0:]

array([ 90, 100, 110, 120])

In [13]:
np333[1,1:, :2]

array([[170, 180],
       [210, 220]])

In [30]:
np333[0,1:, 2:,],np333[1, :2, 2:]

(array([[ 70,  80],
        [110, 120]]), array([[150, 160],
        [190, 200]]))

In [33]:
np3333 = np333.reshape(6,4)

In [34]:
np3333

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200],
       [210, 220, 230, 240]])

In [35]:
np3333[1:-1,2:]

array([[ 70,  80],
       [110, 120],
       [150, 160],
       [190, 200]])