<a href="https://colab.research.google.com/github/nureeee/numpy-pandas/blob/main/210522_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

####불리언값으로 선택하기

In [2]:
names = np.array(['Bob', 'Joe', 'Will'])

In [3]:
data = np.random.randn(3, 2)

In [4]:
names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [5]:
data

array([[ 0.90832061, -0.46174242],
       [ 0.00786162,  0.68232609],
       [ 0.05794769,  0.58661429]])

In [7]:
names == 'Bob'

array([ True, False, False])

In [8]:
data[names=='Bob']

array([[ 0.90832061, -0.46174242]])

In [9]:
data[names=='Bob', 2:]   ## name == 'Bob'인 로우에서 2: 컬럼을 선택했다.

array([], shape=(1, 0), dtype=float64)

In [11]:
names != 'BOb'

array([ True,  True,  True])

In [12]:
cond = names == 'Bob'
data[~cond]

array([[0.00786162, 0.68232609],
       [0.05794769, 0.58661429]])

In [13]:
mask = (names == 'Bob') | (names == 'Will')  ## '|'는 or과 같은 의미
mask

array([ True, False,  True])

In [16]:
data[data<0] = 0
data

array([[0.90832061, 0.        ],
       [0.00786162, 0.68232609],
       [0.05794769, 0.58661429]])

In [18]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        ],
       [0.00786162, 0.68232609],
       [7.        , 7.        ]])

#### 팬시색인

In [19]:
arr = np.empty((8, 4))

In [21]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [22]:
arr[[4, 3, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [28]:
arr = np.arange(32).reshape(8, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [31]:
arr[[1, 5, 3, 7], [3, 1, 2, 0]]  ## 각각의 색인 튜플에 대응하는 1차원 배열이 선택된다.

array([ 7, 21, 14, 28])

In [33]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [36]:
arr = np.arange(16).reshape(2, 2, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [38]:
arr.swapaxes(1, 2)  ## 두 개의 축 번호를 받아서 배열을 뒤바꾼다.

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [39]:
arr.mean(axis=1)

array([[ 2.,  3.,  4.,  5.],
       [10., 11., 12., 13.]])

In [40]:
arr.cumsum(axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8, 10, 12, 14],
        [16, 18, 20, 22]]])

In [42]:
arr.cumprod(axis=1)  ## comprod ; 각 원소의 누적곱

array([[[  0,   1,   2,   3],
        [  0,   5,  12,  21]],

       [[  8,   9,  10,  11],
        [ 96, 117, 140, 165]]])

In [44]:
arr = np.random.randn(100)
(arr > 0).sum()  ##양수인 원소의 개수

52

In [45]:
arr

array([ 2.38107399e+00, -2.12281811e+00,  1.44166009e+00, -5.40815368e-01,
        3.58963174e-01, -1.37912062e-01, -4.42997135e-01,  7.46957884e-01,
       -1.82969639e+00,  1.18432930e+00, -3.93773583e-01,  1.32899834e+00,
        9.71685944e-01, -1.11146133e+00,  7.04278178e-01, -4.43334980e-01,
        5.28372832e-02,  2.65843299e+00, -9.05502861e-01, -1.16574119e+00,
       -9.47213703e-01, -1.07870750e+00,  1.23417294e+00,  9.99597097e-01,
        1.01237925e+00, -5.64969634e-01, -1.70285095e+00, -1.34725650e+00,
       -1.21347056e+00,  1.45048120e+00, -8.41450824e-01,  3.05984994e+00,
        9.15705286e-01,  4.37326597e-01, -1.32043809e-01, -5.41603003e-01,
       -6.24829367e-01,  1.78005666e+00,  8.16701605e-02,  1.58023716e+00,
       -2.80696744e-01, -1.76605332e+00, -2.41256349e-01, -6.29298901e-02,
        7.83028154e-01, -9.25494326e-01, -8.09519559e-01,  2.11579150e+00,
       -6.68095412e-01,  9.33328039e-01, -5.33677582e-01,  2.68346431e-01,
       -1.21132101e+00,  

In [46]:
from pandas import Series, DataFrame

In [47]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [48]:
obj.values

array([ 4,  7, -5,  3])

In [49]:
obj.index ## range(4)와 같다.

RangeIndex(start=0, stop=4, step=1)

In [50]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [51]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [52]:
obj2['a']

-5

In [53]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64