In [18]:
import numpy as np

In [ ]:
dan2 = [i*2 for i in range(1,10)]
dan3 = [i*3 for i in range(1,10)]
dan4 = [i*4 for i in range(1,10)]
dan5 = [i*5 for i in range(1,10)]
dan6 = [i*6 for i in range(1,10)]
dan7 = [i*7 for i in range(1,10)]
dan8 = [i*8 for i in range(1,10)]
dan9 = [i*9 for i in range(1,10)]

In [19]:
gdan = np.array([dan2, dan3, dan4, dan5, dan6, dan7, dan8, dan9])

In [20]:
gdan

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [21]:
gdan.astype(np.int16)

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]], dtype=int16)

In [23]:
gdan[1]+50

array([53, 56, 59, 62, 65, 68, 71, 74, 77])

In [24]:
gdan[3]*100

array([ 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500])

In [25]:
gdan.T

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  6,  8, 10, 12, 14, 16, 18],
       [ 6,  9, 12, 15, 18, 21, 24, 27],
       [ 8, 12, 16, 20, 24, 28, 32, 36],
       [10, 15, 20, 25, 30, 35, 40, 45],
       [12, 18, 24, 30, 36, 42, 48, 54],
       [14, 21, 28, 35, 42, 49, 56, 63],
       [16, 24, 32, 40, 48, 56, 64, 72],
       [18, 27, 36, 45, 54, 63, 72, 81]])