<a href="https://colab.research.google.com/github/nureeee/numpy-pandas/blob/main/210520_%EC%98%A4%ED%9B%84%EC%88%98%EC%97%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##

In [284]:
import pandas as pd
import numpy as np

In [285]:
n1 = np.random.randint(0, 100, 10)  ##0~100 중에서 랜덤 값 10개 선택

In [286]:
n1

array([ 8, 46, 94, 77, 88, 10, 50, 86, 52, 70])

In [287]:
type(n1)

numpy.ndarray

In [288]:
n1.shape

(10,)

In [289]:
n1.ndim

1

In [290]:
n1.size

10

In [291]:
n1.nbytes  ##총 바이트 값

80

In [292]:
n1.itemsize

8

In [293]:
n = n1.copy()

In [294]:
n[:]

array([ 8, 46, 94, 77, 88, 10, 50, 86, 52, 70])

In [295]:
n[0:10]

array([ 8, 46, 94, 77, 88, 10, 50, 86, 52, 70])

In [296]:
n[0:10:2]

array([ 8, 94, 88, 50, 52])

In [297]:
n[0:10:3]

array([ 8, 77, 50, 70])

In [298]:
n[::-1]

array([70, 52, 86, 50, 10, 88, 77, 94, 46,  8])

In [299]:
n[::-2]

array([70, 86, 10, 77, 46])

In [300]:
n.reshape(2, 5)

array([[ 8, 46, 94, 77, 88],
       [10, 50, 86, 52, 70]])

In [301]:
n.reshape(5, 2)

array([[ 8, 46],
       [94, 77],
       [88, 10],
       [50, 86],
       [52, 70]])

In [302]:
n.sort()

In [303]:
n1.sort(axis=1)  ##에러

AxisError: ignored

In [ ]:
n1.sort?  ##도움말 보기

In [ ]:
n2 = np.random.randint(1, 100, 12)

In [ ]:
n2

In [ ]:
n2.reshape(3, 4)

In [ ]:
n2.reshape(2, 6)

In [ ]:
n2.reshape(4, 3)

In [ ]:
n21 = np.arange(1, 17, dtype = np.int16)

In [ ]:
n = n21.reshape(4, 4)

In [ ]:
n

In [ ]:
n[ :, : ]

In [ ]:
n[0, 3]

In [ ]:
n[0:2, 1:3]

In [ ]:
n[1:, 2:]

In [ ]:
n[2:, :2]

In [ ]:
n[2:, 1:3]

In [ ]:
n[0, 1:3] == 0

In [ ]:
a = [2, 3, 5]

In [ ]:
a ==5

In [ ]:
n[0]<5

In [ ]:
n[0][0] ==100

In [ ]:
n>10

###operation : '+, -, *, /'
###비교 : >, <, >=ㅡ <=, ==, !=



In [ ]:
n[:, 0] 

In [ ]:
n[:, -1] = 100

In [ ]:
n

In [ ]:
n.sum()

In [ ]:
n[0].sum()

In [ ]:
n.max

In [ ]:
n.max(axis = 0)

In [ ]:
n.std()

In [ ]:
np.median(n)

In [ ]:
np.median(n[0])

In [ ]:
np.zeros(5)

In [ ]:
np.ones(5)

In [ ]:
np.tri(10)

In [ ]:
np.empty(6) 

In [ ]:
np.zeros((2, 6))

In [ ]:
np.ones((3, 4))

In [ ]:
np.array([4, 5, 6, 7])

In [ ]:
n7 = np.array([4, 5, 6, 7])

In [ ]:
n7.nbytes

In [ ]:
n8 = np.array([4, 5, 6, 7], np.int32)

In [ ]:
n8.nbytes

In [ ]:
k = [i for i in range(5, 51, 5)]

In [ ]:
k

In [ ]:
type(k)

In [ ]:
t = (i for i in range(10, 101, 10)) 

In [ ]:
t

In [ ]:
type(t)

In [ ]:
n10 = np.array(k)

In [ ]:
n10

In [ ]:
n11 = np.array(t)

In [ ]:
n11

In [ ]:
s1 = pd.Series([2, 4, 6, 8])

In [ ]:
type(s1)

In [ ]:
s1.shape

In [ ]:
s1.ndim

In [ ]:
s1.nbytes

In [ ]:
s1.items

In [ ]:
s1.index

In [ ]:
s1  ##좌측의 값은 '인텍스'
    ##인텍스를 묵시적으로 입력함

In [ ]:
s1.index = ['T', 'K', 'B', 'Q'] ## 인텍스를 명시적으로 나타냄

In [ ]:
s1

In [ ]:
s1[0]

In [ ]:
s1[2]

In [ ]:
s1['T']

In [ ]:
s1.iloc[1]  #i는 인텍스를 나타냄

In [ ]:
s1.loc[1]  ##에러

In [ ]:
s1.loc['T']

---

In [ ]:
pd1 = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
type(pd1)

In [ ]:
pd1.shape

In [ ]:
p = pd1.copy()

In [ ]:
p

In [ ]:
p.head(3)

In [ ]:
p.tail(3)

In [ ]:
pd2 = pd.read_csv('/content/sample_data/sc.csv', encoding = 'cp949')  ##ansi로 저장되어 있으면 뒤에 인코딩 'cp949' 

In [ ]:
pd2

In [ ]:
p = pd2.copy()

In [ ]:
p

In [ ]:
pd2 = pd.read_csv('/content/sample_data/sc.csv',header=None, encoding = 'cp949')

In [ ]:
pd2

In [ ]:
p = pd2.copy()

In [ ]:
p

In [ ]:
p.columns = ['이름', '국어', '영어', '수학']

In [ ]:
p

In [ ]:
 p.shape

In [ ]:
type(p)

In [ ]:
p.ndim

In [ ]:
p.size

In [ ]:
p.info()

In [ ]:
p.describe()

In [ ]:
p.index

In [ ]:
p.columns

In [ ]:
p['총점'] = p['국어']+p['수학']+p['영어']

In [ ]:
p['총점']

In [ ]:
p['평균'] = p['총점']/3

In [ ]:
p['평균']

In [ ]:
p.iloc[:, 1:4].sum() 

In [ ]:
p.iloc[:,3:] > 70  ##문제
                   ###수학점수가 70점 이상인 사람만 뽑아내기

In [ ]:
p[3, 0] ##에러, p[3][0]도 에러

In [ ]:
p.iloc[3, 0]

In [ ]:
p['이름']

In [ ]:
p.loc[:,['이름']]

In [ ]:
p.loc[:,['이름','수학']]

In [ ]:
p.iloc[4:7, 1:3]

In [ ]:
p['국어'] >=70  ##마스킹

In [ ]:
p.iloc[:, 1:] >= 70

In [ ]:
p.loc[3:6]

In [ ]:
p.iloc[:, 2:] <= 60

In [ ]:
p.loc[:, ['국어', '영어', '수학']] <= 60  ##i는 inteser를 의미한다.

In [ ]:
p.sum()

In [ ]:
p.mean()  ##반평균

In [ ]:
p.sum(axis = 1)

In [ ]:
p['국어'].value_counts()  ##점수 분포도 

In [ ]:
p['국어'].value_counts(ascending = False)

In [ ]:
p['국어'].sort_values()

In [ ]:
p['국어'].sort_values(ascending=False)

In [ ]:
p.sort_values(by = '영어')

In [ ]:
p.sort_values(by = ['영어', '수학'])  ##값의 배열이 바뀐 것은 아님

In [ ]:
p

In [ ]:
p.sort_values(by = ['영어', '수학'], inplace=True)  ##데이터 프레임이 바뀜

In [ ]:
p

In [ ]:
p['영어']+5  ##영어 과목만 5점 올린다.

In [306]:
def get_grade(x):
    grade = ''
    if x >= 90:
        grade = '수'
    elif x >= 80:
        grade = '우'
    elif x >= 70:
        grade = '미'
    elif x >= 60:
        grade = '양' 
    else: grade = '가'
    return grade 

p['평가'] = p['평균'].apply(lambda x: get_grade(x))     

In [307]:
p

이름  국어  영어  수학   총점         평균 평가
6  임꺽정  15  35  45   95  31.666667  가
3  황진이  35  45  20  100  33.333333  가
9  이누리  50  45  60  155  51.666667  가
1  강감찬  75  80  95  250  83.333333  우
4  안중근  90  85  90  265  88.333333  우
0  이순신  85  87  90  262  87.333333  우
8  정몽주  90  90  95  275  91.666667  수
7  김정호  90  95  80  265  88.333333  우
5  박문수  95  98  96  289  96.333333  수
2  한석봉  99  98  99  296  98.666667  수