In [8]:
import numpy as np
import pandas as pd

In [9]:
t = [i*3 for i in range(1, 11)]

In [10]:
np1 = np.array(t)

In [11]:
np1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np1.reshape(2, 5)

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

In [13]:
np1 +1

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [14]:
np2 = np1.reshape(2, 5)

In [20]:
np2

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

In [23]:
np2 = np2[0, 2:4]

In [24]:
np2

array([ 9, 12])

In [26]:
np1.reshape(5, 2)

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24],
       [27, 30]])

In [27]:
np1.dtype

dtype('int64')

In [28]:
np1.astype(np.int16)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30], dtype=int16)

In [29]:
np1.nbytes

80

In [31]:
np1.itemsize

8

In [32]:
np1.mean()

16.5

In [34]:
np1.mean(axis=0)

16.5