<a href="https://colab.research.google.com/github/nureeee/numpy-pandas/blob/main/210523_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import pandas as pd

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [4]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [5]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [6]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [7]:
arr = np.arange(10)
np.save('some_array.npy', arr)

In [8]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.savez('array_archive.npz', a=arr, b=arr)

In [10]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [1]:
from pandas import Series, DataFrame

In [3]:
import pandas as pd

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
data = {'state': ['ohio', 'ohio', 'ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)


In [7]:
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [8]:
frame.head()

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [9]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [10]:
frame['state']

0      ohio
1      ohio
2      ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [11]:
frame.loc[3]

state    Nevada
year       2001
pop         2.4
Name: 3, dtype: object

In [12]:
frame['debt'] = 16.5
frame

state  year  pop  debt
0    ohio  2000  1.5  16.5
1    ohio  2001  1.7  16.5
2    ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [16]:
frame['debt'] = np.arange(6.)
frame

state  year  pop  debt
0    ohio  2000  1.5   0.0
1    ohio  2001  1.7   1.0
2    ohio  2002  3.6   2.0
3  Nevada  2001  2.4   3.0
4  Nevada  2002  2.9   4.0
5  Nevada  2003  3.2   5.0

In [17]:
frame.T

0     1     2       3       4       5
state  ohio  ohio  ohio  Nevada  Nevada  Nevada
year   2000  2001  2002    2001    2002    2003
pop     1.5   1.7   3.6     2.4     2.9     3.2
debt      0     1     2       3       4       5

In [18]:
a = [1, 2, 3]

In [19]:
a.append(4)

In [20]:
a

[1, 2, 3, 4]

In [23]:
for i in range(4):
    for j in range(4):
        if j >i:
            break
        print(i, j)

0 0
1 0
1 1
2 0
2 1
2 2
3 0
3 1
3 2
3 3


In [24]:
sequence = [1, 2, 0, 4, 6, 5, 2, 1]
tot_until_5 =0
for value in sequence:
    if value ==5:
        break
    tot_until_5 += value

In [25]:
print(tot_until_5)

13


In [27]:
x = 256
total = 0
while x > 0:
    if total >500:
        break
    total += x
    x = x//2

In [28]:
print(total)

504
