<a href="https://colab.research.google.com/github/nureeee/numpy-pandas/blob/main/210601_%EC%98%A4%EC%A0%84%EC%88%98%EC%97%85_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### numpy 기초

In [6]:
import numpy as np

py_list = [1, 2, 3]
arr1 = np.array(py_list)
arr1

### np.full


In [7]:
np.ones((2, 3))*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [8]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [10]:
np.zeros((2, 3)) ## 딥러닝이나 머신러닝에서 편향 초기값

array([[0., 0., 0.],
       [0., 0., 0.]])

### 점구간 만들기
  * 시각화에서 선을 긋는 용도로 사용한다.
  

In [11]:
np.linspace(1, 10, 3) ## 1부터 10까지 3개의 수를 균일된 구간으로 만든다. --> 2개의 구간을 생성                    

array([ 1. ,  5.5, 10. ])

In [12]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Random
 * 랜덤 배열은 딥러닝에서 매개변수 (' 가중치 ', '편향')을 초기화 하기  위해서 사용
 * 초기화 : 최초에 가지고 있는 값을 만드는 과정
 * 생성자 : 객체 초기화 매소드
    -크래스를 이용해서 객체를 만들 때 객채가 처음 가지고 있어야 하는 값을 세팅하는 값

## 완전 랜덤
* np.random.rand : 정규 분포나 균등분포가 아닌 완벽한 랜덤

In [13]:
 np.random.rand(2, 3)

array([[0.61499295, 0.91641651, 0.62913558],
       [0.57462038, 0.84283607, 0.17669336]])

In [14]:
 np.random.rand(2, 3, 4)

array([[[0.93329618, 0.2001906 , 0.6943016 , 0.02162291],
        [0.12129182, 0.58139346, 0.31097282, 0.13762525],
        [0.48375319, 0.64973198, 0.48688298, 0.73259726]],

       [[0.77501437, 0.19303057, 0.55912562, 0.99292152],
        [0.20830322, 0.17459091, 0.95629296, 0.32064949],
        [0.59577099, 0.18103724, 0.31373277, 0.59046623]]])

## 정규분포 랜덤 만들기
* np.random.randn


In [16]:
np.random.randn(16)

array([-1.08705739,  1.10649373,  1.90127571,  0.54764424, -0.37489545,
        0.36256714,  1.25987766,  0.71891592, -1.54784625,  0.05822709,
       -1.02986163,  1.202636  ,  0.76784972,  0.46993799, -1.62727867,
        0.61843244])

In [17]:
np.random.randn(2, 3, 4)

array([[[ 1.6414566 , -1.15357886, -0.2933396 , -1.33523377],
        [ 1.4560713 , -3.03511176,  0.30989906, -0.05664192],
        [-0.48873687,  0.853081  , -0.15873939,  1.19938963]],

       [[ 0.2075203 ,  0.07445718,  0.80778006, -1.15824117],
        [-2.1232969 , -1.43293132, -0.65575229, -1.18925492],
        [-0.45222181, -1.78278571, -1.60928829, -0.02172523]]])

## 균등분포

 * np.random.uniform

In [18]:
np.random.uniform(1.0, 3.0, size=(3, 4))

array([[1.5224676 , 1.93428562, 2.36591608, 2.46072311],
       [1.32206899, 1.66099454, 1.53842967, 2.44917451],
       [2.8386483 , 1.45137414, 1.25483727, 2.74320192]])

## 정수 랜덤 샘플링
 * 'np.random.choice'
 * 샘플링 : 전체에서 일부를 추출하는 행위
 *딥러인엥서는 mini-batch를 만듣ㄹ 때 사용
 

In [20]:
np.random.choice(10, size=(2, 3))  ## 0~9까지의 정수를 랜덤하게 (2, 3) 배열 형태로 추출

array([[3, 7, 8],
       [5, 9, 6]])

In [21]:
## 배열 내에서도 랜덤 추출이 가능하다

arr = np.arange(1, 6)
np.random.choice(arr, size=(2, 3))

array([[4, 5, 5],
       [2, 5, 2]])

In [22]:
## 중복추출x
np.random.choice(arr, size=(2, 2), replace=False)

array([[5, 4],
       [3, 1]])

In [ ]:
np.random.choice(arr, size=(2, 3), replace=False)  ## 중복추출이 안되기 때문에 에러 발생

## 랜덤 정수 배열 만들기
 * np.random.randint

In [27]:
arr1 = np.random.randint(1, 100, size=(5, ))
arr1

array([54, 55, 68, 79, 75])

In [28]:
arr2 = np.random.randint(1, 100, size=(5, 1))
arr2


array([[93],
       [40],
       [76],
       [37],
       [ 8]])

## 다차원 배열에 대한 내용
 * notion에 설명 2_1 행열에 자세히 나와있음

In [29]:
## 행벡터의 모양을 하고 있지만 1차원 배열이기 때문에 열벡터로 따져야 한다
h_1 = np.array([180.1, 174.5, 163.3])
h_1

array([180.1, 174.5, 163.3])

In [31]:
h_2 = np.array([[180.2],
               [175.5], [163.3]])

h_2

array([[180.2],
       [175.5],
       [163.3]])

## 행열
 * 2차원 배열
 * 1차원 배열인 벡터가 여러 개 모여 있는 것 


## 텐서 
* 3ㅏ차원이상의 배열을 의미한다
* 3차원 배열은 2차원 배열리 모여있다
* 4차원 배열은 3차원 배열이 모여있다
* N차원 배욜을 그냥 텐서라고 한다
* 텐서의 개념을 활용히면 모든 배열의 모양을 이야기 할 수 있다.

* tensorflow는 
* 구글에서 제공하는 딥러닝 프레임워크

In [32]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [33]:
arr[:, 1:3, 1:]  ## [axis=0, axis=1, axis=2]

array([[[ 5,  6],
        [ 8,  9]],

       [[17, 18],
        [20, 21]],

       [[29, 30],
        [32, 33]]])

In [35]:
arr = np.arange(36).reshape(2, 3, 3, 2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [36]:
arr[0, :, :, 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [37]:
arr[0, ..., 0]  ## 중간 값을 전부 선택할 때

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### 차원 추가 ( 차원 수 확장)

In [38]:
arr = np.random.rand(28, 28)
arr.shape

(28, 28)

In [39]:
temp_arr = arr[np.newaxis, :, :,np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

In [40]:
temp_arr = arr[np.newaxis, ...,np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

## 차원 쥐어 짜기
* np.squeeze
* 개수가 1인 차원의 내용을 없애는 기법

In [42]:
temp_arr.shape

(1, 28, 28, 1)

In [43]:
temp_squeeze = np.squeeze(temp_arr)
temp_squeeze.shape

(28, 28)

## 평탄화
* 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것 !!!!!!!!( 중요)
* ravel : 원본 배열을 평탄화 시킨 참조 배열을 만들어 낸다
* flatten : 원본배열을 평탄화 시킨 복사된 배열을 만들어 낸다

In [44]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [45]:
x

array([[10,  2, 10,  9, 12],
       [ 1,  3,  6,  3,  9],
       [ 9,  1, 12,  5,  2]])

### ravel

In [47]:
temp = np.ravel(x)  ## 보이기만 평평하게 보여준다
temp.shape

(15,)

In [48]:
temp

array([10,  2, 10,  9, 12,  1,  3,  6,  3,  9,  9,  1, 12,  5,  2])

In [49]:
temp[0] = 100
temp

array([100,   2,  10,   9,  12,   1,   3,   6,   3,   9,   9,   1,  12,
         5,   2])

In [50]:
x  ## temp의 값과 x의 값이 둘다 변함

array([[100,   2,  10,   9,  12],
       [  1,   3,   6,   3,   9],
       [  9,   1,  12,   5,   2]])

In [52]:
x[1][3] = 55
temp

array([100,   2,  10,   9,  12,   1,   3,   6,  55,   9,   9,   1,  12,
         5,   2])

###flatten
* 원본 데이터를 안전하게 보관할 수 있어 플랫튼을 더 많이 사용한다.

##reshape
* 형상을 바꿔준다
* tip 함수 내의 모든 숫자를 곱했을 대 스칼라 원소의 개수와 같으면 된다.

In [58]:
x = np.arange(20)
x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
x.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [60]:
x.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
x.reshape(2, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [63]:
x.reshape(2, -1, 2)  ## 조커와 같은 역할을 한다. 단 -1은 한번만 사용할 수 있다. 무조건 한개의 값만 들어간다.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])